import glob
import time
import os

configfile: "config/snakemake_config.yaml"

SAMPLES = list(config["samples"].keys())

include: "rules/check_files.smk"
include: "rules/assembly.smk"
include: "rules/annotation.smk"
include: "rules/trimming.smk"
include: "rules/genbank.smk"
include: "rules/nhmmer.smk"
include: "rules/error_correction.smk"
include: "rules/images.smk"
include: "rules/parse_results.smk"

wildcard_constraints:
    sample = r"[A-Za-z0-9_]+",
    seed = r"[A-Za-z0-9._:-]+",
    kmer = r"\d+"

rule all:
    input:
        "resources/table2asn.linux64",
        "resources/nhmmer_db.hmm",
        expand("workflow/reports/{sample_id}/parse_results.done", sample_id=SAMPLES)
