executor: local
use-singularity: true
singularity-args: "-B {WORKDIR}:/mnt -B {WORKDIR}/tmp:/tmp --pwd /mnt --no-home --writable"
latency-wait: 30
show-failed-logs: True
keep-going: False
printshellcmds: True
rerun-incomplete: True

set-threads:
  all: 1
  download_getorganelle_db: 1
  run_novoplasty_mitos2: 1
  run_getorganelle_mitos2: 1
  run_novoplasty_cpgavas2: 1
  run_getorganelle_cpgavas2: 1
  run_novoplasty_chloe: 1
  run_getorganelle_chloe: 1
  create_hash: 1
  run_novoplasty: 1
  run_getorganelle: 8
  run_mitohifi: 8
  get_novoplasty_assemblies: 1
  get_getorganelle_assemblies: 1
  check_shortreads_files: 1
  check_longreads_files: 1
  check_adapters: 1
  check_nhmmer_db: 1
  extract_table2asn: 1
  index_hmmer_db: 1
  run_novoplasty_bwa_index: 1
  run_novoplasty_bwa_mem: 4
  run_novoplasty_samtools_index: 1
  run_novoplasty_pilon: 2
  run_getorganelle_bwa_index: 1
  run_getorganelle_bwa_mem: 4
  run_getorganelle_samtools_index: 1
  run_getorganelle_pilon: 2
  write_gb_novoplasty_mitos2: 1
  write_gb_novoplasty_chloe: 1
  write_gb_novoplasty_cpgavas2: 1
  write_gb_getorganelle_mitos2: 1
  write_gb_getorganelle_chloe: 1
  write_gb_getorganelle_cpgavas2: 1
  rotate_mito_gb_novoplasty: 1
  rotate_cpgavas_gb_novoplasty: 1
  rotate_chloe_gb_novoplasty: 1
  rotate_mito_gb_getorganelle: 1
  rotate_cpgavas_gb_getorganelle: 1
  rotate_chloe_gb_getorganelle: 1
  get_genbank_fastas: 1
  run_blastn: 1
  run_recruitment_plot: 1
  run_bwa_index_rotated: 1
  run_bwa_mem_rotated: 4
  run_samtools_depth: 1
  run_samtools_depth_rotated: 1
  run_depth_plot: 1
  run_ogdraw_mito: 1
  run_ogdraw_chloro: 1
  get_mito_ncRNA_sequences_short: 1
  run_ncRNA_nhmmer_short: 4
  get_mito_intergenes_sequences_short: 1
  run_intergenes_nhmmer_short: 4
  get_mito_ncRNA_sequences_long: 1
  run_ncRNA_nhmmer_long: 4
  get_mito_intergenes_sequences_long: 1
  run_intergenes_nhmmer_long: 4
  get_chloro_intergenes_sequences: 1
  run_intergenes_nhmmer_chloro: 4
  get_chloro_ncRNA_sequences: 1
  run_ncRNA_nhmmer_chloro: 4
  run_fastp: 4
  check_reference: 1
  check_fasta_longreads: 1
  parse_results: 1
